config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }
  resources :rooms do
    member do
      get :reserve
    end
  end
  root to: "rooms#index"
  get "home", to: 'pages#home'
  get "about", to:'pages#about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hotel.rb
class Hotel < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
  mount_uploader :image, RoomUploader
  belongs_to :hotel

  validates :length, 
            :width,
            :description,
            :hotel_id,
            :image,
            presence: true

  validates :length, :width, numericality: { only_float: true }
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include DeviseWhitelist
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
    extend ActiveSupport::Concern

    included do
        before_action :configure_permitted_parameters, if: :devise_controller?
    end

    private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all
    before_action :set_room, only: [:show, :edit, :destroy, :reserve]
    
    def index
        @rooms = Room.all
    end

    def show
    end

    def new
        @room = Room.new
    end

    def create
        @room = Room.new(room_params)

        respond_to do |format|
            if @room.save
                format.html{ redirect_to rooms_path, notice: 'Room succesfully created'}
            else 
                format.html { render :new }
            end
        end
    end

    def edit
    end

    def update
        @room = Room.find(params[:id])

        respond_to do |format|
            if @room.update(room_params)
                format.html { redirect_to rooms_path, notice: 'Room succesfully updated'}
            else
                format.html { render :edit }
            end 
        end
    end

    def destroy
        @room.destroy

        respond_to do |format|
            format.html { redirect_to rooms_url, notice: 'Room deleted' }
        end
    end

    def reserve
        @room.update(taken: true)
        redirect_to rooms_url, notice: 'Habitación apartada'
    end

    private
    def set_room
        @room = Room.find(params[:id])
    end

    def room_params
        params.require(:room).permit(:id, 
                                    :length, 
                                    :width, 
                                    :image, 
                                    :hotel_id,
                                    :taken,
                                    :description)
                            .with_defaults(hotel_id: 1,
                                            image: "http://via.placeholder.com/700x400",
                                            taken: 0)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render 'shared/navbar' %>
      <div class="site-wrapper">
        <div class="site-wrapper-inner">
          <div class="cover-container">
            <%= yield %>
          </div>
        </div>
      </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="cover-heading">About</div>
  <hr>

  <div class="row">
    <div class="col-md-6 my-auto">
        <h3>Direction</h3>
        <p>Yucatan, Mexico</p>

        <p>Phone number</p>
        <p>+52 5555555555</p>

        <h3>Email</h3>
        <p><a href="mailto:example@gmail.com?subject=Contact" "email me">Email me</a></p>
    </div>

    <div class="col-md-6">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d59530.8302061216!2d-90.06519156424994!3d21.1652532359902!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x85ff544a77ffb431%3A0x26d0f35f4844ea1b!2sPlaya%20Sisal!5e0!3m2!1ses!2smx!4v1676874078494!5m2!1ses!2smx" width="450" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>

  </div>

</div>


<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
    <% if room.errors.any? %>
        <div>
            <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved: </h2>

            <ul>
                <% room.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="row">
        <div class="col mb-6">
            <div class="form-group">
                <%= form.label :Length %>
                <%= form.text_field :length, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= form.label :Width %>
                <%= form.text_field :width, class: 'form-control' %>
            </div>
        
            <div class="form-group">
                <label class="btn btn-primary">
                    Imagen <%= form.file_field :image, style: 'display:none' %>
                </label>
            </div>
        </div>

        <div class="col-md-6">
            <div class="form-group">
                <%= form.label :Description %>
                <%= form.text_area :description, class: 'form-control', rows: 13 %>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <%= form.submit 'Save', class: 'btn btn-primary btn-block' %>
            </div>
        </div>
    </div>
<% end %>

app/views/rooms/edit.html.erb
<div class="container">
    <h1>Edit Room</h1>
    <%= render 'form', room: @room %>
</div>

app/views/rooms/index.html.erb
<main role="main">
    <section class="jumbotron text-center">
        <div class="container">
            <h1>Welcome!<h1>
            <p class="lead text-muted">
                In this page you can find all our romms available. If you're interested in one, just click on <strong>Separate</strong>!
            </p>
        </div>
    </section>
    <div class="album py-5 bg-light">
        <div class="container">
            <% if logged_in?(:site_admin) %>
                <div class="text-center my-3">
                    <%= link_to 'Create Room', new_room_path, class: 'btn btn-primary' %>
                </div>
            <% end %>

            <div class="row">
                <% @rooms.each do |room| %>
                  <div class="col-md-4">
                    <div class="card mb-4 shadow-sm text-center">
                        <%= image_tag (room.image).to_s %>
                        <div class="card-body">
                            <p class="card-text">
                                <%= room.description.split(" ").first(15).join(" ") %>
                            </p>
                            <%= link_to 'Details', room_path(room), class: 'btn btn-warning' %>
                            <% if !room.taken %>
                                <%= link_to 'Reserve', reserve_room_path(room), class: 'btn btn-success' %>
                            <% end %>
                        </div>
                    </div>
                  </div>
                <% end %>
            </div>
        </div>
    </div>
</main>

app/views/rooms/new.html.erb
<div class="container my-5">
    <div class="col">
        <h1>New Room</h1>

        <%= render 'form', room: @room %>

        <%= link_to 'Back', rooms_path %>
    </div>
</div>

app/views/rooms/show.html.erb
<div class=container>
    <div class="row">
        <div class="col-md-7">
            <%= image_tag (@room.image).to_s, style: 'width:100%;' %>
        </div>
        <div class="col-md-5">
            <p><%= @room.description %></p>
            <p>Length: <%= @room.length %></p>
            <p>Width: <%= @room.width %></p>
            <% if !@room.taken %>
                <%= link_to 'Reserve', reserve_room_path(@room), class: 'my-3 btn btn-success' %>
            <% end %>
        </div>
        <% if logged_in?(:site_admin)%>
            <div>
                <%= link_to 'Edit', edit_room_path(@room), class: 'btn btn-warning' %>
                <%= link_to 'Delete', @room, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this room?' }, class: 'btn btn-warning' %>
            </div>
        <% end %>
    </div>
    <div class="row">
        <%= link_to 'Back', rooms_path, class: 'btn btn-secondary my-3' %>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" >
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
            <%= link_to 'Home', rooms_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
            <%= link_to 'About', about_path, class: "nav-link" %>
            </li>
            <% if current_user %>
            <%= link_to 'Logout', destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
            <% else %>
            <%= link_to 'Register', new_user_registration_path, class: "nav-link" %>
            <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
            <% end %>
        </ul>
        </div>
    </div>
</nav>